GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Evento 1",
    "description": "Um novo evento 1",
    "date": "2024-06-24T00:00:00",
    "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "Evento 1 edited",
    "description": "Um novo evento 1",
    "date": "2024-06-24T00:00:00",
    "price": 100
}


###
DELETE http://localhost:3000/events/{{ eventId }}

###
GET http://localhost:3000/events/{{ eventId }}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
    "name": "Spot 1"
}
